import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://jvdiasfilms.com.br";
const POSTS_DIR = path.join(ROOT, "ensaios", "posts");
const ENSAIOS_DIR = path.join(ROOT, "ensaios");
const GENERATED_ESSAY = "<!-- Generated by scripts/build-site.mjs: essay -->";
const PERSON_ID = `${SITE_URL}/#person`;
const WEBSITE_ID = `${SITE_URL}/#website`;
const DEFAULT_IMAGE = `${SITE_URL}/assets/images/optimized/og-jvdias.jpg`;
const PROFILE_IMAGE = `${SITE_URL}/assets/images/optimized/foto-sobre.jpg`;
const CF_BEACON = `  <!-- Cloudflare Web Analytics -->
  <script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "5111ddaf126b4d4da730a4847b7031a9"}'></script>`;

// Registro central de páginas top-level: consumido por renderSitemap() e pelo
// loop de injeção de canonical no fim do script. Entradas sem `file` entram só
// no sitemap (páginas geradas já embutem o próprio canonical ao renderizar).
const TOP_LEVEL_PAGES = [
  { file: "index.html", loc: "/", priority: "1.0" },
  { file: "about.html", loc: "/about", priority: "0.8" },
  { loc: "/ensaios/", priority: "0.8" },
  { file: "teleprompter/index.html", loc: "/teleprompter/", priority: "0.8" },
  { file: "teleprompter/privacy.html", loc: "/teleprompter/privacy", priority: "0.3" },
];

const read = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");
const write = (file, text) => fs.writeFileSync(path.join(ROOT, file), text, "utf8");

function validatePosts(posts) {
  if (!Array.isArray(posts)) throw new Error("posts.json must contain an array.");
  const slugs = new Set();
  const markdown = new Map();
  for (const [index, post] of posts.entries()) {
    const fail = (message) => { throw new Error(`Post ${index + 1} (${post?.slug ?? "unknown"}): ${message}`); };
    if (!post || typeof post !== "object" || Array.isArray(post)) fail("must be an object.");
    if (typeof post.slug !== "string" || !/^[a-z0-9-]+$/.test(post.slug)) fail("invalid slug.");
    if (["index", "post"].includes(post.slug)) fail("reserved slug.");
    if (slugs.has(post.slug)) fail("duplicate slug.");
    slugs.add(post.slug);
    if (post.draft !== undefined && typeof post.draft !== "boolean") fail("draft must be a boolean.");
    // Drafts may have incomplete editorial content, but still need a safe, unique slug.
    if (post.draft) continue;
    for (const field of ["title", "excerpt"]) {
      if (typeof post[field] !== "string" || !post[field].trim()) fail(`${field} is required.`);
    }
    const date = typeof post.date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(post.date)
      ? new Date(`${post.date}T12:00:00Z`) : null;
    if (!date || Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== post.date) fail("invalid date; use YYYY-MM-DD.");
    if (!Array.isArray(post.tags) || post.tags.some((tag) => typeof tag !== "string" || !tag.trim())) fail("tags must be an array of non-empty strings.");
    for (const field of ["coverImage", "coverAlt", "coverPosition", "videoUrl", "location"]) {
      if (post[field] !== undefined && typeof post[field] !== "string") fail(`${field} must be a string.`);
    }
    if (post.coverImage) {
      const image = path.resolve(ENSAIOS_DIR, post.coverImage);
      if (!image.startsWith(ROOT + path.sep) || !fs.existsSync(image) || !fs.statSync(image).isFile()) fail("coverImage must reference an existing site image.");
    }
    if (post.videoUrl && !/^https?:\/\/(?:www\.)?vimeo\.com\/\d+(?:[/?#].*)?$/.test(post.videoUrl)) fail("videoUrl must be a Vimeo video URL.");
    const file = path.join(POSTS_DIR, `${post.slug}.md`);
    if (!fs.existsSync(file) || !fs.statSync(file).isFile()) fail("missing markdown file.");
    markdown.set(post.slug, fs.readFileSync(file, "utf8"));
  }
  return markdown;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(value) {
  return escapeHtml(value);
}

function inlineEmphasis(value) {
  let out = escapeHtml(value);
  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  return out;
}

function inlineMarkdown(value) {
  // Parse links before formatting so emphasis cannot alter URL attributes.
  const links = /\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)/g;
  let output = "";
  let cursor = 0;
  for (const match of value.matchAll(links)) {
    output += inlineEmphasis(value.slice(cursor, match.index));
    output += `<a href="${escapeAttr(match[2])}">${inlineEmphasis(match[1])}</a>`;
    cursor = match.index + match[0].length;
  }
  return output + inlineEmphasis(value.slice(cursor));
}

function renderMarkdown(md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const html = [];
  let para = [];
  let quote = [];
  let list = null;

  function flushPara() {
    if (!para.length) return;
    html.push(`<p>${inlineMarkdown(para.join(" "))}</p>`);
    para = [];
  }

  function flushQuote() {
    if (!quote.length) return;
    html.push(`<blockquote><p>${inlineMarkdown(quote.join(" "))}</p></blockquote>`);
    quote = [];
  }

  function flushList() {
    if (!list) return;
    html.push(`<${list.type}>${list.items.map((item) => `<li>${inlineMarkdown(item)}</li>`).join("")}</${list.type}>`);
    list = null;
  }

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      flushPara();
      flushQuote();
      flushList();
      continue;
    }

    const unordered = trimmed.match(/^[-*]\s+(.+)$/);
    const ordered = trimmed.match(/^\d+\.\s+(.+)$/);
    if (unordered || ordered) {
      flushPara();
      flushQuote();
      const type = unordered ? "ul" : "ol";
      if (list && list.type !== type) flushList();
      if (!list) list = { type, items: [] };
      list.items.push(unordered?.[1] || ordered?.[1]);
      continue;
    }

    flushList();
    if (trimmed.startsWith(">")) {
      flushPara();
      quote.push(trimmed.replace(/^>\s?/, ""));
      continue;
    }

    flushQuote();
    if (trimmed === "---") {
      flushPara();
      html.push("<hr>");
    } else if (trimmed.startsWith("### ")) {
      flushPara();
      html.push(`<h3>${inlineMarkdown(trimmed.slice(4))}</h3>`);
    } else if (trimmed.startsWith("## ")) {
      flushPara();
      html.push(`<h2>${inlineMarkdown(trimmed.slice(3))}</h2>`);
    } else {
      para.push(trimmed);
    }
  }

  flushPara();
  flushQuote();
  flushList();
  return html.join("\n");
}

function formatDate(date) {
  return new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function formatMonth(date) {
  return new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR", {
    month: "long",
    year: "numeric",
  });
}

function readingTime(md) {
  const words = md.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200));
}

function absoluteUrl(url) {
  return `${SITE_URL}/${url.replace(/^\.\.\//, "").replace(/^\.\//, "")}`;
}

function imageDimensions(imagePath) {
  if (!imagePath) return null;
  const local = path.normalize(path.join(ENSAIOS_DIR, imagePath));
  if (!fs.existsSync(local)) return null;

  const buffer = fs.readFileSync(local);
  if (buffer.length >= 24 && buffer.toString("ascii", 1, 4) === "PNG") {
    return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
  }

  if (buffer[0] !== 0xff || buffer[1] !== 0xd8) return null;

  let offset = 2;
  const sofMarkers = new Set([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf]);
  while (offset < buffer.length) {
    while (buffer[offset] === 0xff) offset++;
    const marker = buffer[offset++];
    if (marker === 0xda || marker === 0xd9) break;
    if (offset + 2 > buffer.length) break;
    const length = buffer.readUInt16BE(offset);
    if (length < 2 || offset + length > buffer.length) break;
    if (sofMarkers.has(marker)) {
      return {
        height: buffer.readUInt16BE(offset + 3),
        width: buffer.readUInt16BE(offset + 5),
      };
    }
    offset += length;
  }

  return null;
}

function imageDimensionAttrs(imagePath) {
  const dimensions = imageDimensions(imagePath);
  return dimensions ? `width="${dimensions.width}" height="${dimensions.height}"` : "";
}

function mergeAttrs(...attrs) {
  return attrs.filter(Boolean).join(" ");
}

function safeJsonLd(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function structuredDataScript(graph) {
  return `<script type="application/ld+json" id="structured-data">\n${safeJsonLd({ "@context": "https://schema.org", "@graph": graph })}\n  </script>`;
}

function personNode() {
  return {
    "@type": "Person",
    "@id": PERSON_ID,
    name: "J. V. Dias",
    url: `${SITE_URL}/`,
    image: PROFILE_IMAGE,
    jobTitle: "Diretor visual, filmmaker e artista 3D",
    email: "mailto:joaodias@jvdias.com",
    sameAs: ["https://www.linkedin.com/in/JvDiasM"],
    knowsAbout: ["cinema", "direção visual", "3D", "direção de fotografia", "produção audiovisual", "pipeline de render"],
  };
}

function websiteNode() {
  return {
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    url: `${SITE_URL}/`,
    name: "J. V. Dias",
    inLanguage: "pt-BR",
    publisher: { "@id": PERSON_ID },
  };
}

function essayIndexStructuredData(posts) {
  const url = `${SITE_URL}/ensaios/`;
  return [
    personNode(),
    websiteNode(),
    {
      "@type": "CollectionPage",
      "@id": `${url}#webpage`,
      url,
      name: "Ensaios — J. V. Dias",
      description: "Ensaios sobre cinema, direção visual, 3D e processo criativo por J. V. Dias.",
      inLanguage: "pt-BR",
      isPartOf: { "@id": WEBSITE_ID },
      about: { "@id": PERSON_ID },
      mainEntity: { "@id": `${url}#blog` },
    },
    {
      "@type": "Blog",
      "@id": `${url}#blog`,
      url,
      name: "Ensaios",
      inLanguage: "pt-BR",
      author: { "@id": PERSON_ID },
      blogPost: posts.map((post) => ({ "@id": `${SITE_URL}/ensaios/${post.slug}#article` })),
    },
    {
      "@type": "ItemList",
      "@id": `${url}#posts`,
      itemListElement: posts.map((post, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${SITE_URL}/ensaios/${post.slug}`,
        name: post.title,
      })),
    },
  ];
}

function essayPostStructuredData(post, md, readTime) {
  const url = `${SITE_URL}/ensaios/${post.slug}`;
  const image = absoluteUrl(post.coverImage || "../assets/images/optimized/og-jvdias.jpg");
  const wordCount = md.trim().split(/\s+/).filter(Boolean).length;
  return [
    personNode(),
    websiteNode(),
    {
      "@type": "WebPage",
      "@id": `${url}#webpage`,
      url,
      name: `${post.title} — J. V. Dias`,
      description: post.excerpt,
      inLanguage: "pt-BR",
      isPartOf: { "@id": WEBSITE_ID },
      about: { "@id": PERSON_ID },
      primaryImageOfPage: image,
      mainEntity: { "@id": `${url}#article` },
    },
    {
      "@type": "BlogPosting",
      "@id": `${url}#article`,
      mainEntityOfPage: { "@id": `${url}#webpage` },
      headline: post.title,
      description: post.excerpt,
      image,
      datePublished: post.date,
      dateModified: post.date,
      author: { "@id": PERSON_ID },
      publisher: { "@id": PERSON_ID },
      inLanguage: "pt-BR",
      keywords: post.tags || [],
      timeRequired: `PT${readTime}M`,
      wordCount,
    },
  ];
}

function webpCandidate(imagePath) {
  if (!imagePath) return "";
  const webp = imagePath.replace(/\.(jpg|jpeg|png)$/i, ".webp");
  const local = path.join(ENSAIOS_DIR, webp);
  return fs.existsSync(local) ? webp : "";
}

function pictureMarkup(imagePath, alt, attrs = "") {
  if (!imagePath) return "";
  const webp = webpCandidate(imagePath);
  const attr = mergeAttrs(imageDimensionAttrs(imagePath), attrs);
  const attrText = attr ? ` ${attr}` : "";
  return `<picture>
            ${webp ? `<source srcset="${escapeAttr(webp)}" type="image/webp">` : ""}
            <img src="${escapeAttr(imagePath)}" alt="${escapeAttr(alt)}"${attrText}>
          </picture>`;
}

function renderHeader(ariaCurrentEnsaios) {
  const ensaiosCurrent = ariaCurrentEnsaios ? ` aria-current="${ariaCurrentEnsaios}"` : "";
  return `  <header class="site-header">
    <nav class="nav">
      <a href="/" class="logo visible">J. V. Dias</a>
      <ul class="nav-links">
        <li><a href="/#works">Projetos</a></li>
        <li><a href="/ensaios/"${ensaiosCurrent}>Ensaios</a></li>
        <li class="nav-item-teleprompter"><a href="/teleprompter/">Teleprompter</a></li>
        <li><a href="/about">Sobre</a></li>
        <li><a href="/#contact">Contato</a></li>
      </ul>
    </nav>
  </header>`;
}

function renderFooter() {
  return `  <footer class="site-footer">
    <div class="footer-inner">
      <span class="footer-name">J. V. Dias</span>
      <nav class="footer-nav" aria-label="Rodapé">
        <a href="/#works">Projetos</a>
        <span class="footer-sep">·</span>
        <a href="/ensaios/">Ensaios</a>
        <span class="footer-sep">·</span>
        <a href="/teleprompter/">Teleprompter</a>
        <span class="footer-sep">·</span>
        <a href="/about">Sobre</a>
      </nav>
      <div class="footer-links">
        <a href="mailto:joaodias@jvdias.com">joaodias@jvdias.com</a>
        <span class="footer-sep">·</span>
        <a href="https://www.linkedin.com/in/JvDiasM" target="_blank" rel="noopener noreferrer">LinkedIn</a>
      </div>
    </div>
  </footer>`;
}

function renderEssayIndex(posts) {
  const entries = posts.map((post) => {
    const style = post.coverPosition ? `style="object-position: ${escapeAttr(post.coverPosition)};" ` : "";
    const cover = post.coverImage
      ? `<div class="ensaio-cover">${pictureMarkup(post.coverImage, post.coverAlt || "", `${style}loading="lazy" decoding="async"`)}</div>`
      : "";

    return `      <!-- ENSAIO: ${post.slug} -->
      <a href="${post.slug}" class="ensaio-entry">
        ${cover}
        <div class="ensaio-entry-content">
          <time class="ensaio-date" datetime="${post.date}">${formatDate(post.date)}</time>
          <h2 class="ensaio-entry-title">${escapeHtml(post.title)}</h2>
          <p class="ensaio-excerpt">${escapeHtml(post.excerpt)}</p>
          <div class="ensaio-meta">
            ${post.tags.map((tag) => `<span class="ensaio-tag">${escapeHtml(tag)}</span>`).join("\n            ")}
          </div>
        </div>
      </a>`;
  }).join("\n\n");

  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ensaios — J. V. Dias</title>
  <meta name="description" content="Ensaios sobre cinema, direção visual, 3D e processo criativo por J. V. Dias.">
  <meta name="theme-color" content="#0a0a0a">
  <link rel="canonical" href="${SITE_URL}/ensaios/">

  <meta property="og:type" content="website">
  <meta property="og:url" content="${SITE_URL}/ensaios/">
  <meta property="og:title" content="Ensaios — J. V. Dias">
  <meta property="og:description" content="Ensaios sobre cinema, direção visual, 3D e processo criativo.">
  <meta property="og:image" content="${SITE_URL}/assets/images/optimized/og-jvdias.jpg">
  <meta name="twitter:card" content="summary_large_image">
  ${structuredDataScript(essayIndexStructuredData(posts))}

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;400&family=Inter:wght@400;500&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="../assets/images/Favicon.png">
  <link rel="apple-touch-icon" href="../assets/images/apple-touch-icon.png">
  <link rel="alternate" type="application/rss+xml" title="Ensaios — J. V. Dias" href="${SITE_URL}/ensaios/feed.xml">
  <link rel="stylesheet" href="../css/styles.css">
</head>
<body>

  <a class="skip-link" href="#conteudo">Pular para o conteúdo</a>

${renderHeader("page")}

  <main class="ensaios-page" id="conteudo">

    <div class="ensaios-masthead">
      <span class="ensaios-dateline">Vol. 01 · 2026</span>
      <h1 class="ensaios-title">Ensaios</h1>
      <p class="ensaios-subtitle">Textos sobre imagem, processo e construção visual.</p>
    </div>

    <div class="ensaio-list" id="ensaio-list">

${entries}

    </div>

  </main>

${renderFooter()}

${CF_BEACON}
</body>
</html>
`;
}

function renderStaticPost(post, index, published, md) {
  const prev = published[index + 1];
  const next = published[index - 1];
  const dateStr = formatDate(post.date);
  const readTime = readingTime(md);
  const coverPosition = post.coverPosition || "center";
  const coverAttrs = `style="object-position: ${escapeAttr(coverPosition)};" decoding="async"`;
  const cover = post.coverImage
    ? `<div class="ensaio-cover-hero">${pictureMarkup(post.coverImage, post.coverAlt || "", coverAttrs)}</div>`
    : "";
  const tags = post.tags?.length
    ? `<div class="ensaio-tags">${post.tags.map((tag) => `<span class="ensaio-tag">${escapeHtml(tag)}</span>`).join("")}</div>`
    : "";
  const videoId = post.videoUrl?.match(/vimeo\.com\/(\d+)/)?.[1];
  const video = videoId
    ? `<div class="ensaio-video"><div class="ensaio-video-player"><iframe src="https://player.vimeo.com/video/${videoId}?title=0&byline=0&portrait=0&dnt=1" allow="autoplay; fullscreen; picture-in-picture" title="Vídeo: ${escapeAttr(post.title)}" loading="lazy" frameborder="0"></iframe></div></div>`
    : "";
  const nav = prev || next
    ? `<nav class="ensaio-nav">
        ${prev ? `<a href="${prev.slug}" class="ensaio-nav-link ensaio-nav-prev"><span class="ensaio-nav-label">&larr; Anterior</span><span class="ensaio-nav-title">${escapeHtml(prev.title)}</span></a>` : "<span></span>"}
        ${next ? `<a href="${next.slug}" class="ensaio-nav-link ensaio-nav-next"><span class="ensaio-nav-label">Próximo &rarr;</span><span class="ensaio-nav-title">${escapeHtml(next.title)}</span></a>` : "<span></span>"}
      </nav>`
    : "";

  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(post.title)} — J. V. Dias</title>
  ${GENERATED_ESSAY}
  <meta name="description" content="${escapeAttr(post.excerpt)}">
  <meta name="theme-color" content="#0a0a0a">
  <link rel="canonical" href="${SITE_URL}/ensaios/${post.slug}">

  <meta property="og:type" content="article">
  <meta property="og:url" content="${SITE_URL}/ensaios/${post.slug}">
  <meta property="og:title" content="${escapeAttr(post.title)} — J. V. Dias">
  <meta property="og:description" content="${escapeAttr(post.excerpt)}">
  <meta property="og:image" content="${absoluteUrl(post.coverImage || "../assets/images/optimized/og-jvdias.jpg")}">
  <meta property="article:published_time" content="${post.date}">
  <meta name="twitter:card" content="summary_large_image">
  ${structuredDataScript(essayPostStructuredData(post, md, readTime))}

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;400&family=Inter:wght@400;500&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="../assets/images/Favicon.png">
  <link rel="apple-touch-icon" href="../assets/images/apple-touch-icon.png">
  <link rel="alternate" type="application/rss+xml" title="Ensaios — J. V. Dias" href="${SITE_URL}/ensaios/feed.xml">
  <link rel="stylesheet" href="../css/styles.css">
</head>
<body>

  <a class="skip-link" href="#conteudo">Pular para o conteúdo</a>

${renderHeader("true")}

  <main class="ensaio-page" id="conteudo">
    <a href="/ensaios/" class="back-link">&larr; Ensaios</a>

    <article class="ensaio-article">
      ${cover}

      <header class="ensaio-header">
        <h1 class="ensaio-title">${escapeHtml(post.title)}</h1>
        <div class="ensaio-info"><time datetime="${post.date}">${dateStr}</time><span class="ensaio-info-sep">·</span><span>${readTime} min de leitura</span></div>
      </header>

      ${video}

      <div class="ensaio-body">
${renderMarkdown(md)}
      </div>

      <div class="ensaio-signature">
        <div class="ensaio-signature-rule" aria-hidden="true">· · ·</div>
        <div class="ensaio-signature-author">— J. V. Dias</div>
        <div class="ensaio-signature-place">${escapeHtml(post.location || "São Paulo")}, ${formatMonth(post.date)}</div>
      </div>

      ${tags}
    </article>

    ${nav}
  </main>

${renderFooter()}

${CF_BEACON}
</body>
</html>
`;
}

function renderSitemap(posts) {
  const pages = [
    ...TOP_LEVEL_PAGES,
    ...fs.readdirSync(path.join(ROOT, "projects"))
      .filter((file) => file.endsWith(".html"))
      .sort()
      .map((file) => ({ loc: `/projects/${file.replace(/\.html$/, "")}`, priority: "0.7" })),
    ...posts.map((post) => ({ loc: `/ensaios/${post.slug}`, lastmod: post.date, priority: "0.7" })),
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map((page) => `  <url>
    <loc>${SITE_URL}${page.loc}</loc>${page.lastmod ? `\n    <lastmod>${page.lastmod}</lastmod>` : ""}
    <priority>${page.priority}</priority>
  </url>`).join("\n")}
</urlset>
`;
}

function rssDate(date) {
  return new Date(`${date}T12:00:00Z`).toUTCString();
}

function renderFeed(posts, markdown) {
  const items = posts.map((post) => {
    const url = `${SITE_URL}/ensaios/${post.slug}`;
    const md = markdown.get(post.slug);
    const html = renderMarkdown(md).replace(/\]\]>/g, "]]&gt;");
    return `    <item>
      <title>${escapeHtml(post.title)}</title>
      <link>${url}</link>
      <guid isPermaLink="true">${url}</guid>
      <pubDate>${rssDate(post.date)}</pubDate>
      <description>${escapeHtml(post.excerpt)}</description>
      <content:encoded><![CDATA[${html}]]></content:encoded>
    </item>`;
  }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Ensaios — J. V. Dias</title>
    <link>${SITE_URL}/ensaios/</link>
    <atom:link href="${SITE_URL}/ensaios/feed.xml" rel="self" type="application/rss+xml"/>
    <description>Ensaios sobre cinema, direção visual, 3D e processo criativo por J. V. Dias.</description>
    <language>pt-BR</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>
`;
}

function renderRobots() {
  return `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

function upsertCanonical(file, href) {
  const text = read(file);
  const newline = text.includes("\r\n") ? "\r\n" : "\n";
  const canonical = `<link rel="canonical" href="${escapeAttr(href)}">`;
  let found = false;
  const updated = text.replace(/<link\b[^>]*>/gi, (tag) => {
    const rel = tag.match(/\srel\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/i);
    if (!rel || !(rel[1] ?? rel[2] ?? rel[3]).toLowerCase().split(/\s+/).includes("canonical")) return tag;
    if (found) return "";
    found = true;
    return canonical;
  });
  if (found) return updated;
  if (!/<\/head\s*>/i.test(text)) throw new Error(`Cannot inject canonical into ${file}: closing head tag not found.`);
  return text.replace(/<\/head\s*>/i, `  ${canonical}${newline}</head>`);
}

function isGeneratedEssay(text, slug) {
  if (text.includes(GENERATED_ESSAY)) return true;
  // Recognize pre-marker build output without deleting arbitrary HTML in ensaios/.
  if (!text.includes('<main class="ensaio-page" id="conteudo">') || !text.includes('class="ensaio-signature"')) return false;
  const data = text.match(/<script type="application\/ld\+json" id="structured-data">([\s\S]*?)<\/script>/);
  if (!data) return false;
  try {
    return JSON.parse(data[1])["@graph"]?.some((node) =>
      node["@type"] === "BlogPosting" && new URL(node["@id"]).pathname === `/ensaios/${slug}`
    ) ?? false;
  } catch {
    return false;
  }
}

const posts = JSON.parse(read("ensaios/posts/posts.json"));
const markdown = validatePosts(posts);
const published = posts
  .filter((post) => !post.draft)
  .sort((a, b) => new Date(b.date) - new Date(a.date));

// Prepare every output before writing: content/template errors leave the last build intact.
const outputs = new Map([["ensaios/index.html", renderEssayIndex(published)]]);
for (const [index, post] of published.entries()) {
  outputs.set(`ensaios/${post.slug}.html`, renderStaticPost(post, index, published, markdown.get(post.slug)));
}

outputs.set("sitemap.xml", renderSitemap(published));
outputs.set("ensaios/feed.xml", renderFeed(published, markdown));
outputs.set("robots.txt", renderRobots());

for (const page of TOP_LEVEL_PAGES) {
  if (page.file) outputs.set(page.file, upsertCanonical(page.file, `${SITE_URL}${page.loc}`));
}

for (const file of fs.readdirSync(path.join(ROOT, "projects")).filter((name) => name.endsWith(".html"))) {
  outputs.set(`projects/${file}`, upsertCanonical(`projects/${file}`, `${SITE_URL}/projects/${file.replace(/\.html$/, "")}`));
}

const obsolete = fs.readdirSync(ENSAIOS_DIR, { withFileTypes: true })
  .filter((entry) => entry.isFile() && /^[a-z0-9-]+\.html$/.test(entry.name) && !["index.html", "post.html"].includes(entry.name))
  .map((entry) => `ensaios/${entry.name}`)
  .filter((file) => !outputs.has(file) && isGeneratedEssay(read(file), path.basename(file, ".html")));

for (const [file, text] of outputs) write(file, text);
// Only direct, recognized generated essay files are eligible for removal.
for (const file of obsolete) fs.unlinkSync(path.join(ROOT, file));

console.log(`Built ${published.length} essay pages, feed.xml, sitemap.xml, and robots.txt. Removed ${obsolete.length} obsolete essay pages.`);
