import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const script = fileURLToPath(new URL("./build-site.mjs", import.meta.url));
const marker = "<!-- Generated by scripts/build-site.mjs: essay -->";
const page = '<!DOCTYPE html>\n<html><head><title>Fixture</title></head><body>Fixture</body></html>\n';

function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "portfolio-build-test-"));
  t.after(() => {
    // Keep recursive cleanup confined to this test's own temporary directory.
    assert.equal(path.dirname(path.resolve(root)), path.resolve(os.tmpdir()));
    assert.ok(path.basename(root).startsWith("portfolio-build-test-"));
    fs.rmSync(root, { recursive: true, force: true });
  });
  const write = (file, text) => {
    fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    fs.writeFileSync(path.join(root, file), text);
  };
  const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
  const exists = (file) => fs.existsSync(path.join(root, file));
  write("scripts/build-site.mjs", fs.readFileSync(script));
  for (const file of ["index.html", "about.html", "teleprompter/index.html", "teleprompter/privacy.html", "projects/example.html", "ensaios/post.html"]) write(file, page);
  const posts = ["first", "second"].map((slug) => ({ slug, title: slug, excerpt: "Example essay", date: "2026-09-07", tags: ["cinema"], draft: false }));
  for (const post of posts) write(`ensaios/posts/${post.slug}.md`, "## Example\n\nEssay body.");
  const save = (value = posts) => write("ensaios/posts/posts.json", JSON.stringify(value));
  save();
  const build = (success = true, message) => {
    const result = spawnSync(process.execPath, ["scripts/build-site.mjs"], { cwd: root, encoding: "utf8" });
    if (success) assert.equal(result.status, 0, result.stderr);
    else {
      assert.notEqual(result.status, 0);
      if (message) assert.match(result.stderr, message);
    }
  };
  const snapshot = () => {
    const files = {};
    const visit = (directory) => {
      for (const entry of fs.readdirSync(path.join(root, directory), { withFileTypes: true })) {
        const file = path.join(directory, entry.name);
        if (entry.isDirectory()) visit(file);
        else if (/\.(html|xml)$/.test(file) || file === "robots.txt") files[file] = read(file);
      }
    };
    visit("");
    return files;
  };
  return { posts, save, build, read, write, exists, snapshot };
}

test("renders reference links with emphasis and escaped attributes in HTML and RSS", (t) => {
  const f = fixture(t);
  f.write("ensaios/posts/first.md", 'Before [*Film*](https://example.com/watch?a=1&b=2) after.\n\n[Unsafe](javascript:alert) <script>alert(1)</script>\n\n[Label](https://example.com/"quoted")');
  f.build();
  for (const file of ["ensaios/first.html", "ensaios/feed.xml"]) {
    const html = f.read(file);
    assert.ok(html.includes('Before <a href="https://example.com/watch?a=1&amp;b=2"><em>Film</em></a> after.'));
    assert.ok(html.includes('href="https://example.com/&quot;quoted&quot;"'));
    assert.ok(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));
    assert.ok(!html.includes('href="javascript:'));
  }
});

test("updates stale canonical, removes duplicates, inserts missing tags, and is idempotent", (t) => {
  const f = fixture(t);
  f.write("index.html", page.replace("</head>", '<link href="https://old.example/" REL=\'canonical\'>\n<link rel="canonical" href="https://duplicate.example/">\n<link rel="stylesheet" href="/css/styles.css">\n</head>'));
  f.write("about.html", page.replaceAll("\n", "\r\n"));
  f.build();
  const html = f.read("index.html");
  assert.equal((html.match(/rel="canonical"/g) || []).length, 1);
  assert.ok(html.includes('href="https://jvdiasfilms.com.br/"'));
  assert.ok(html.includes('rel="stylesheet"'));
  assert.ok(f.read("projects/example.html").includes('href="https://jvdiasfilms.com.br/projects/example"'));
  assert.ok(f.read("teleprompter/privacy.html").includes('href="https://jvdiasfilms.com.br/teleprompter/privacy"'));
  assert.ok(f.read("about.html").includes('href="https://jvdiasfilms.com.br/about">\r\n</head>'));
  f.build();
  assert.equal(f.read("index.html"), html);
});

test("removes deleted and renamed essays while retaining unrelated HTML and legacy redirect", (t) => {
  const f = fixture(t);
  f.build();
  f.write("ensaios/manual.html", page);
  f.write("ensaios/posts/renamed.md", "Renamed body.");
  f.posts[1].slug = "renamed";
  f.save([f.posts[1]]);
  f.build();
  assert.equal(f.exists("ensaios/first.html"), false);
  assert.equal(f.exists("ensaios/second.html"), false);
  assert.equal(f.exists("ensaios/renamed.html"), true);
  assert.equal(f.read("ensaios/manual.html"), page);
  assert.equal(f.read("ensaios/post.html"), page);
  for (const file of ["ensaios/index.html", "sitemap.xml", "ensaios/feed.xml"]) {
    assert.ok(f.read(file).includes("renamed"));
    assert.doesNotMatch(f.read(file), /(?:\/ensaios\/|href=")(?:first|second)(?:<|#|")/);
  }
});

test("cleans pre-marker output when changed to draft and supports unpublishing all essays", (t) => {
  const f = fixture(t);
  f.build();
  f.write("ensaios/first.html", f.read("ensaios/first.html").replace(marker, ""));
  f.save([{ slug: "first", draft: true }]);
  f.build();
  assert.equal(f.exists("ensaios/first.html"), false);
  assert.equal(f.exists("ensaios/second.html"), false);
  assert.equal(f.exists("ensaios/index.html"), true);
});

test("rejects invalid metadata before changing any published outputs", async (t) => {
  const cases = [
    ["not an array", (f) => f.save({}), /must contain an array/],
    ["null entry", (f) => f.save([null]), /must be an object/],
    ["unsafe slug", (f) => { f.posts[1].slug = "../about"; f.save(); }, /invalid slug/],
    ["reserved slug", (f) => { f.posts[1].slug = "index"; f.save(); }, /reserved slug/],
    ["duplicate slug", (f) => { f.posts[1].slug = "first"; f.save(); }, /duplicate slug/],
    ["impossible date", (f) => { f.posts[1].date = "2026-02-30"; f.save(); }, /invalid date/],
    ["missing title", (f) => { delete f.posts[1].title; f.save(); }, /title is required/],
    ["invalid tags", (f) => { f.posts[1].tags = "cinema"; f.save(); }, /tags must/],
    ["invalid draft", (f) => { f.posts[1].draft = "false"; f.save(); }, /draft must/],
    ["missing cover", (f) => { f.posts[1].coverImage = "../assets/missing.jpg"; f.save(); }, /coverImage must/],
    ["invalid video", (f) => { f.posts[1].videoUrl = "https://example.com/123"; f.save(); }, /videoUrl must/],
    ["missing markdown", (f) => { f.posts[1].slug = "missing"; f.save(); }, /missing markdown/],
  ];
  for (const [name, mutate, error] of cases) {
    await t.test(name, (t) => {
      const f = fixture(t);
      f.build();
      const before = f.snapshot();
      mutate(f);
      f.build(false, error);
      assert.deepEqual(f.snapshot(), before);
    });
  }
});

test("a canonical template error also leaves outputs and obsolete essays intact", (t) => {
  const f = fixture(t);
  f.build();
  f.save([]);
  f.write("about.html", "<html><body>Missing head</body></html>");
  const before = f.snapshot();
  f.build(false, /closing head tag not found/);
  assert.deepEqual(f.snapshot(), before);
});
